{{- if .Values.superblocks.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dataplane-superblocks-key
type: Opaque
data:
  key: {{ .Values.superblocks.key | b64enc }}
{{- end }}
{{- if .Values.secrets.encryptionKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dataplane-secrets-encryption
type: Opaque
data:
  key: {{ .Values.secrets.encryptionKey | b64enc }}
{{- end }}
{{- if .Values.queue.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: queue-redis-token
data:
  token: {{ .Values.queue.token | b64enc }}
{{- end }}
{{- if .Values.kvstore.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kvstore-redis-token
data:
  token: {{ .Values.kvstore.token | b64enc }}
{{- end }}
{{- if .Values.superblocks.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-key
data:
  key: {{ .Values.superblocks.key | b64enc }}
{{- end }}
