{{- if not .Values.superblocks.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superblocks-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
type: Opaque
data:
  SUPERBLOCKS_AGENT_KEY: {{ required "superblocks.agentKey or superblocks.existingSecret is required!" .Values.superblocks.agentKey | b64enc | quote }}
{{- end }}
