---
# Kind cluster configuration with Calico CNI support
# Disables default CNI so Calico can be installed
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # Disable default CNI (kindnetd) to use Calico instead
  disableDefaultCNI: true
  # Calico's default pod subnet
  podSubnet: "192.168.0.0/16"
